"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { createClient, type User } from "@supabase/supabase-js";

const supabase=createClient("https://yytyntrgqkddfsliooke.supabase.co","sb_publishable_r82IW91PSRwRa_dye0g1Cw_qU0zLeDW");
type Member={email:string;display_name:string;color:string;birthday:string|null};
type Visibility={viewer_email:string;owner_email:string};
type CalendarEvent={id:number;title:string;date:string;time:string;endTime:string;owner:string;participants:string[];location:string;note:string;timezone:string;endDate?:string;birthday?:boolean};
const COLORS=["sage","clay","gold","rose","stone"] as const;
const COLOR_NAMES:{[key:string]:string}={sage:"鼠尾草绿",clay:"陶土橘",gold:"麦穗黄",rose:"干燥玫瑰",stone:"岩石灰"};
const ZONES=["Asia/Shanghai","Asia/Tokyo","Asia/Dubai","Europe/Berlin","Europe/London","America/Los_Angeles","America/New_York"];
const ZONE_NAMES:{[key:string]:string}={"Asia/Shanghai":"上海","Asia/Tokyo":"东京","Asia/Dubai":"迪拜","Europe/Berlin":"德国","Europe/London":"伦敦","America/Los_Angeles":"加州","America/New_York":"纽约"};
const EVENT_COLORS:{[key:string]:string}={sage:"#dce0cc",clay:"#ecd7c8",gold:"#eee2bd",rose:"#ead5d2",stone:"#dedbd1"};
const EVENT_LINES:{[key:string]:string}={sage:"#7d835f",clay:"#b87959",gold:"#b2944e",rose:"#b37b78",stone:"#817c6c"};
const HOURS=Array.from({length:25},(_,hour)=>hour);
const HOUR_HEIGHT=56;
function dateKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function nextDateKey(date:string){const [year,month,day]=date.split("-").map(Number);const value=new Date(Date.UTC(year,month-1,day+1));return `${value.getUTCFullYear()}-${String(value.getUTCMonth()+1).padStart(2,"0")}-${String(value.getUTCDate()).padStart(2,"0")}`}
function monday(d:Date){const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function timeTop(time:string){const [hour,minute]=time.split(":").map(Number);return (hour+minute/60)*HOUR_HEIGHT}
function timeFromPosition(position:number){const halfHours=Math.max(0,Math.min(47,Math.floor(position/HOUR_HEIGHT*2)));return `${String(Math.floor(halfHours/2)).padStart(2,"0")}:${halfHours%2?"30":"00"}`}
function nextHour(time:string){const [hour,minute]=time.split(":").map(Number);const total=Math.min(hour*60+minute+60,1439);return `${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`}
function minutes(time:string){const [hour,minute]=time.split(":").map(Number);return hour*60+minute}
function durationMinutes(start:string,end:string){const value=minutes(end)-minutes(start);return value>0?value:value+1440}
function durationHeight(start:string,end:string){return Math.max(40,durationMinutes(start,end)/60*HOUR_HEIGHT-4)}
function zonedParts(value:Date,timezone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(value);return Object.fromEntries(parts.map(part=>[part.type,part.value]))}
function zonedDate(date:string,time:string,timezone:string){const [year,month,day]=date.split("-").map(Number);const [hour,minute]=time.split(":").map(Number);const target=Date.UTC(year,month-1,day,hour,minute);let value=new Date(target);for(let attempt=0;attempt<3;attempt++){const shown=zonedParts(value,timezone);const represented=Date.UTC(Number(shown.year),Number(shown.month)-1,Number(shown.day),Number(shown.hour),Number(shown.minute));value=new Date(value.getTime()+target-represented)}return value}
function localInZone(value:Date,timezone:string){const parts=zonedParts(value,timezone);return {date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`}}
function convertLocal(date:string,time:string,fromZone:string,toZone:string){return localInZone(zonedDate(date,time,fromZone),toZone)}
function eventInZone(event:CalendarEvent,timezone:string){const startInstant=zonedDate(event.date,event.time,event.timezone||"Asia/Shanghai");const endInstant=new Date(startInstant.getTime()+durationMinutes(event.time,event.endTime)*60_000);const start=localInZone(startInstant,timezone);const end=localInZone(endInstant,timezone);return {...event,date:start.date,time:start.time,endTime:end.time,endDate:end.date}}
function weekParts(event:CalendarEvent){if(!event.endDate||event.endDate===event.date)return [event];return [{...event,endTime:"24:00",endDate:event.date},{...event,date:event.endDate,time:"00:00"}]}

export default function Home(){
  const [user,setUser]=useState<User|null>(null);const [member,setMember]=useState<Member|null>(null);const [members,setMembers]=useState<Member[]>([]);const [authReady,setAuthReady]=useState(false);
  const [loginEmail,setLoginEmail]=useState("");const [password,setPassword]=useState("");const [signingIn,setSigningIn]=useState(false);const [authMessage,setAuthMessage]=useState("");
  const [authView,setAuthView]=useState<"login"|"forgot"|"sent">("login");const [recoveryMode,setRecoveryMode]=useState(()=>window.location.hash.includes("type=recovery"));const [settingsOpen,setSettingsOpen]=useState(false);const [adminOpen,setAdminOpen]=useState(false);const [profileOpen,setProfileOpen]=useState(false);const [profileView,setProfileView]=useState<"menu"|"color"|"birthday">("menu");const [birthday,setBirthday]=useState("");const [profileMessage,setProfileMessage]=useState("");const [visibility,setVisibility]=useState<Visibility[]>([]);const [selectedOwners,setSelectedOwners]=useState<string[]>([]);
  const [currentPassword,setCurrentPassword]=useState("");const [newPassword,setNewPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [passwordMessage,setPasswordMessage]=useState("");const [savingPassword,setSavingPassword]=useState(false);
  const [view,setView]=useState<"month"|"week">("month");const [cursor,setCursor]=useState(new Date());const [zone,setZone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone||"Asia/Shanghai");
  const [events,setEvents]=useState<CalendarEvent[]>([]);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<CalendarEvent|null>(null);const [draft,setDraft]=useState({title:"",date:dateKey(new Date()),time:"12:00",endTime:"13:00",timezone:"Asia/Shanghai",participants:[] as string[],location:"",note:""});
  async function load(current?:User|null){const active=current??(await supabase.auth.getUser()).data.user;if(!active){setMember(null);setEvents([]);return}const email=(active.email||"").toLowerCase();const [{data:memberRows},{data:visibilityRows}]=await Promise.all([supabase.from("shared_calendar_members").select("email,display_name,color,birthday").order("created_at"),supabase.from("shared_calendar_visibility").select("viewer_email,owner_email")]);const list=(memberRows||[]) as Member[];const permissions=(visibilityRows||[]) as Visibility[];setMembers(list);setVisibility(permissions);const mine=list.find(m=>m.email.toLowerCase()===email)||null;setMember(mine);setBirthday(mine?.birthday||"");const allowed=email==="elainezhang1110@gmail.com"?list.map(item=>item.email):Array.from(new Set([email,...permissions.filter(row=>row.viewer_email===email).map(row=>row.owner_email)]));setSelectedOwners(current=>{const kept=current.filter(owner=>allowed.includes(owner));return kept.length?kept:allowed});if(!mine){setEvents([]);return}const {data}=await supabase.from("shared_calendar_events").select("id,title,event_date,event_time,end_time,owner_email,participant_emails,location,note,timezone").order("event_date").order("event_time");setEvents((data||[]).map((e:any)=>({id:e.id,title:e.title,date:e.event_date,time:String(e.event_time).slice(0,5),endTime:String(e.end_time).slice(0,5),owner:e.owner_email,participants:e.participant_emails||[],location:e.location,note:e.note,timezone:e.timezone})));}
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{const u=data.session?.user||null;setUser(u);setAuthReady(true);load(u)});const {data}=supabase.auth.onAuthStateChange((event,s)=>{if(event==="PASSWORD_RECOVERY")setRecoveryMode(true);setUser(s?.user||null);load(s?.user||null)});return()=>data.subscription.unsubscribe()},[]);
  const dates=useMemo(()=>{const start=view==="month"?monday(new Date(cursor.getFullYear(),cursor.getMonth(),1)):monday(cursor);return Array.from({length:view==="month"?42:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})},[cursor,view]);
  const label=view==="month"?`${cursor.getFullYear()} 年 ${cursor.getMonth()+1} 月`:`${dates[0].getMonth()+1} 月 ${dates[0].getDate()} 日 — ${dates[6].getMonth()+1} 月 ${dates[6].getDate()} 日`;
  async function signIn(event:FormEvent){event.preventDefault();if(!loginEmail.trim()||!password)return;setSigningIn(true);setAuthMessage("");const {error}=await supabase.auth.signInWithPassword({email:loginEmail.trim(),password});if(error)setAuthMessage("邮箱或密码不正确");setSigningIn(false)}
  async function sendRecovery(event:FormEvent){event.preventDefault();if(!loginEmail.trim())return;setSigningIn(true);setAuthMessage("");const redirectTo=`${window.location.origin}${window.location.pathname}`;const {error}=await supabase.auth.resetPasswordForEmail(loginEmail.trim(),{redirectTo});if(error)setAuthMessage(error.message.includes("rate limit")?"发送过于频繁，请稍后再试":"暂时无法发送重设邮件，请稍后再试");else setAuthView("sent");setSigningIn(false)}
  function passwordValidation(){if(newPassword.length<8)return "新密码至少需要 8 位";if(newPassword!==confirmPassword)return "两次输入的新密码不一致";return ""}
  async function updatePassword(fromRecovery=false){const validation=passwordValidation();if(validation){setPasswordMessage(validation);return}if(!fromRecovery&&!currentPassword){setPasswordMessage("请输入当前密码");return}setSavingPassword(true);setPasswordMessage("");const attributes=fromRecovery?{password:newPassword}:{password:newPassword,currentPassword};const {error}=await supabase.auth.updateUser(attributes);if(error)setPasswordMessage(fromRecovery?"重设链接可能已失效，请重新发送邮件":"当前密码不正确，或新密码不符合要求");else{setPasswordMessage("密码已更新");setCurrentPassword("");setNewPassword("");setConfirmPassword("");if(fromRecovery){setRecoveryMode(false);window.history.replaceState({},"",window.location.pathname)}}setSavingPassword(false)}
  function startAdd(date?:string,time="12:00"){setEditing(null);setDraft({title:"",date:date||dateKey(new Date()),time,endTime:nextHour(time),timezone:"Asia/Shanghai",participants:[],location:"",note:""});setOpen(true)}
  function startEdit(e:CalendarEvent){if(e.owner.toLowerCase()!==user?.email?.toLowerCase())return;setEditing(e);setDraft({title:e.title,date:e.date,time:e.time,endTime:e.endTime,timezone:e.timezone||"Asia/Shanghai",participants:e.participants||[],location:e.location||"",note:e.note||""});setOpen(true)}
  async function save(){if(!user||!member||!draft.title.trim()||draft.endTime===draft.time)return;const values={title:draft.title.trim(),event_date:draft.date,event_time:draft.time,end_time:draft.endTime,participant_emails:draft.participants,location:draft.location,note:draft.note,timezone:draft.timezone,updated_at:new Date().toISOString()};if(editing)await supabase.from("shared_calendar_events").update(values).eq("id",editing.id);else await supabase.from("shared_calendar_events").insert({...values,owner_user_id:user.id,owner_email:member.email});setOpen(false);await load(user)}
  async function remove(){if(!editing||!user)return;await supabase.from("shared_calendar_events").delete().eq("id",editing.id);setOpen(false);await load(user)}
  async function changeColor(color:string){if(!member||members.some(m=>m.email!==member.email&&m.color===color))return;const {error}=await supabase.from("shared_calendar_members").update({color}).eq("email",member.email);if(!error)await load(user)}
  async function saveBirthday(){if(!member)return;setProfileMessage("");const {error}=await supabase.from("shared_calendar_members").update({birthday:birthday||null}).eq("email",member.email);if(error)setProfileMessage("生日暂时无法保存");else{setProfileMessage("生日已保存，会自动显示在每一年");await load(user)}}
  async function toggleVisibility(viewer:string,owner:string){if(user?.email?.toLowerCase()!=="elainezhang1110@gmail.com"||viewer===owner)return;const exists=visibility.some(row=>row.viewer_email===viewer&&row.owner_email===owner);const result=exists?await supabase.from("shared_calendar_visibility").delete().eq("viewer_email",viewer).eq("owner_email",owner):await supabase.from("shared_calendar_visibility").insert({viewer_email:viewer,owner_email:owner});if(!result.error)await load(user)}
  if(!authReady)return <main className="login-shell"><div className="login-card"><p className="eyebrow">SHARED CALENDAR</p><h1>正在检查登录状态…</h1></div></main>;
  if(recoveryMode)return <main className="login-shell"><section className="login-card"><div className="login-mark">↻</div><p className="eyebrow">RESET PASSWORD</p><h1>设置新密码</h1><p className="login-copy">重设链接验证成功，请为你的 Shared Calendar 账户设置新密码。</p><label>新密码<input type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="至少 8 位"/></label><label>确认新密码<input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="再次输入新密码"/></label><button className="primary login-action" onClick={()=>updatePassword(true)} disabled={savingPassword}>{savingPassword?"正在保存…":"保存新密码"}</button>{passwordMessage&&<p className={`auth-message ${passwordMessage==="密码已更新"?"success":""}`}>{passwordMessage}</p>}</section></main>;
  if(!user&&authView==="forgot")return <main className="login-shell"><section className="login-card"><div className="login-mark">↻</div><p className="eyebrow">RESET PASSWORD</p><h1>找回密码</h1><p className="login-copy">输入你的受邀邮箱，我们会发送一封重设密码邮件。</p><form onSubmit={sendRecovery}><label>邮箱地址<input type="email" autoComplete="email" value={loginEmail} onChange={e=>setLoginEmail(e.target.value)} placeholder="name@example.com" autoFocus/></label><button className="primary login-action" type="submit" disabled={signingIn}>{signingIn?"正在发送…":"发送重设邮件"}</button></form><button className="text-action" onClick={()=>{setAuthView("login");setAuthMessage("")}}>返回登录</button>{authMessage&&<p className="auth-message">{authMessage}</p>}</section></main>;
  if(!user&&authView==="sent")return <main className="login-shell"><section className="login-card sent-card"><div className="login-mark success-mark">✓</div><p className="eyebrow">EMAIL SENT</p><h1>请检查邮箱</h1><p className="login-copy">如果该邮箱可以使用，你会收到一封来自 Supabase 的重设密码邮件。点击邮件中的链接即可设置新密码。</p><p className="sent-email">{loginEmail}</p><button className="text-action" onClick={()=>{setAuthView("login");setAuthMessage("")}}>返回登录</button></section></main>;
  if(!user)return <main className="login-shell"><section className="login-card"><div className="login-mark">S</div><p className="eyebrow">PRIVATE</p><h1>Shared Calendar</h1><p className="login-copy">仅限获邀成员使用邮箱和密码登录。</p><form onSubmit={signIn}><label>邮箱地址<input type="email" autoComplete="email" value={loginEmail} onChange={e=>setLoginEmail(e.target.value)} placeholder="name@example.com"/></label><label>密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="输入密码"/></label><button className="primary login-action" type="submit" disabled={signingIn}>{signingIn?"正在登录…":"登录"}</button></form><button className="text-action forgot-action" onClick={()=>{setAuthView("forgot");setAuthMessage("")}}>忘记密码？</button>{authMessage&&<p className="auth-message">{authMessage}</p>}</section></main>;
  if(!member)return <main className="login-shell"><section className="login-card"><div className="login-mark">!</div><p className="eyebrow">ACCESS PENDING</p><h1>邮箱尚未获邀</h1><p className="login-copy">{user.email} 已通过邮箱验证，但尚未加入 Shared Calendar 的获邀名单。</p><button className="primary login-action" onClick={()=>supabase.auth.signOut()}>退出并更换邮箱</button></section></main>;
  const colors=Object.fromEntries(members.map(m=>[m.email,m.color]));
  function eventStyle(event:CalendarEvent){const participantColors=[event.owner,...event.participants].map(email=>EVENT_COLORS[colors[email]||"stone"]);const size=100/participantColors.length;const stops=participantColors.flatMap((color,index)=>[`${color} ${index*size}%`,`${color} ${(index+1)*size}%`]).join(",");return {background:`linear-gradient(to bottom, ${stops})`,borderLeftColor:EVENT_LINES[colors[event.owner]||"stone"]}}
  function matchesFilter(event:CalendarEvent){return selectedOwners.includes(event.owner)||event.participants.some(email=>selectedOwners.includes(email))}
  function toggleOwner(email:string){setSelectedOwners(current=>current.includes(email)?current.length===1?current:current.filter(owner=>owner!==email):[...current,email])}
  function toggleParticipant(email:string){setDraft({...draft,participants:draft.participants.includes(email)?draft.participants.filter(item=>item!==email):[...draft.participants,email]})}
  function changeDraftTimezone(timezone:string){const start=convertLocal(draft.date,draft.time,draft.timezone,timezone);const sourceEndDate=draft.endTime>draft.time?draft.date:nextDateKey(draft.date);const end=convertLocal(sourceEndDate,draft.endTime,draft.timezone,timezone);setDraft({...draft,date:start.date,time:start.time,endTime:end.time,timezone})}
  const isAdmin=user.email?.toLowerCase()==="elainezhang1110@gmail.com";const allowedOwners=isAdmin?members:members.filter(item=>item.email===member.email||visibility.some(row=>row.viewer_email===member.email&&row.owner_email===item.email));
  const birthdayEvents=dates.flatMap((date,dateIndex)=>allowedOwners.flatMap((item,memberIndex)=>item.birthday&&item.birthday.slice(5)===dateKey(date).slice(5)?[{id:-(dateIndex*100+memberIndex+1),title:`${item.display_name} 的生日`,date:dateKey(date),time:"09:00",endTime:"10:00",owner:item.email,participants:[],location:"",note:"每年自动重复",timezone:zone,birthday:true} as CalendarEvent]:[]));
  const shownEvents=[...events.map(event=>eventInZone(event,zone)),...birthdayEvents];const weekEvents=shownEvents.flatMap(weekParts);
  return <main className="app-shell" onClick={()=>profileOpen&&setProfileOpen(false)}><header className="topbar"><div><p className="eyebrow">PRIVATE</p><h1>Shared Calendar</h1></div><div className="top-actions"><button className="primary" onClick={()=>startAdd()}>＋ 新行程</button><div className="profile-wrap" onClick={event=>event.stopPropagation()}><button className={`profile-avatar ${member.color}`} aria-label="打开个人设置" aria-expanded={profileOpen} onClick={()=>{setProfileOpen(!profileOpen);setProfileView("menu");setProfileMessage("")}}>{member.display_name.slice(0,1).toUpperCase()}</button>{profileOpen&&<section className="profile-popover"><header><span className={`profile-avatar small ${member.color}`}>{member.display_name.slice(0,1).toUpperCase()}</span><div><strong>{member.display_name}</strong><small>{user.email}</small></div></header>{profileView==="menu"?<div className="profile-menu"><button onClick={()=>setProfileView("color")}><span>●</span><b>我的颜色</b><small>{COLOR_NAMES[member.color]}　›</small></button><button onClick={()=>{setProfileOpen(false);setSettingsOpen(true);setPasswordMessage("")}}><span>⌁</span><b>账户与安全</b><small>修改密码　›</small></button><button onClick={()=>setProfileView("birthday")}><span>♢</span><b>生日设置</b><small>{member.birthday?member.birthday.slice(5).replace("-","/"):"未设置"}　›</small></button>{isAdmin&&<button onClick={()=>{setProfileOpen(false);setAdminOpen(true)}}><span>◇</span><b>管理员设置</b><small>日历权限　›</small></button>}</div>:profileView==="color"?<div className="profile-detail"><button className="profile-back" onClick={()=>setProfileView("menu")}>‹ 返回</button><h3>选择个人颜色</h3><div className="profile-colors">{COLORS.map(color=><button key={color} aria-label={COLOR_NAMES[color]} className={`profile-color ${color} ${member.color===color?"selected":""}`} disabled={members.some(m=>m.email!==member.email&&m.color===color)} onClick={()=>changeColor(color)}/>)}</div><p>更换后，以前和以后添加的行程都会同步使用新颜色。</p></div>:<div className="profile-detail"><button className="profile-back" onClick={()=>setProfileView("menu")}>‹ 返回</button><h3>生日设置</h3><label>生日<input type="date" value={birthday} onChange={e=>setBirthday(e.target.value)}/></label><button className="primary birthday-save" onClick={saveBirthday}>保存生日</button><p>{profileMessage||"保存后会自动出现在每一年的对应日期。"}</p></div>}</section>}</div></div></header>
  <section className="toolbar"><div className="move"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+(view==="month"?-1:0),cursor.getDate()+(view==="week"?-7:0)))}>‹</button><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+(view==="month"?1:0),cursor.getDate()+(view==="week"?7:0)))}>›</button></div><strong>{label}</strong><div className="toolbar-right"><details className="member-filter"><summary>{selectedOwners.length===allowedOwners.length?"所有可见成员":`已选 ${selectedOwners.length} 人`}</summary><div>{allowedOwners.map(item=><label key={item.email}><input type="checkbox" checked={selectedOwners.includes(item.email)} onChange={()=>toggleOwner(item.email)}/><i className={`dot ${item.color}`}/>{item.display_name}</label>)}</div></details><select value={zone} onChange={e=>setZone(e.target.value)}>{ZONES.map(z=><option key={z}>{z}</option>)}</select><div className="segment"><button className={view==="week"?"active":""} onClick={()=>setView("week")}>周</button><button className={view==="month"?"active":""} onClick={()=>setView("month")}>月</button></div></div></section>
  {view==="month"?<section className="calendar month"><div className="weekdays">{["一","二","三","四","五","六","日"].map(x=><span key={x}>周{x}</span>)}</div><div className="grid">{dates.map(d=>{const key=dateKey(d);const dayEvents=shownEvents.filter(e=>e.date===key&&matchesFilter(e));return <button className={`day ${key===dateKey(new Date())?"today":""} ${d.getMonth()!==cursor.getMonth()?"muted":""}`} key={key} onClick={()=>startAdd(key)}><span className="day-number">{d.getDate()}</span><span className="event-list">{dayEvents.map(e=><span key={`${e.id}-${e.date}`} className={`event ${e.birthday?"birthday-event":""}`} style={eventStyle(e)} onClick={x=>{x.stopPropagation();if(!e.birthday)startEdit(events.find(item=>item.id===e.id)! )}}>{!e.birthday&&<b>{e.time}–{e.endTime}</b>}{e.title}</span>)}</span></button>})}</div></section>:<section className="calendar week"><div className="week-scroll"><div className="week-head"><span className="time-corner">时间</span>{dates.map((d,index)=><span className={dateKey(d)===dateKey(new Date())?"current-day":""} key={dateKey(d)}>周{["一","二","三","四","五","六","日"][index]}<b>{d.getMonth()+1}/{d.getDate()}</b></span>)}</div><div className="week-body"><div className="time-axis">{HOURS.map(hour=><span key={hour} style={{top:hour*HOUR_HEIGHT}}>{String(hour).padStart(2,"0")}:00</span>)}</div>{dates.map(d=>{const key=dateKey(d);const dayEvents=weekEvents.filter(e=>e.date===key&&matchesFilter(e));return <div className={`week-column ${key===dateKey(new Date())?"today-column":""}`} key={key} role="button" tabIndex={0} aria-label={`${key} 添加行程`} onClick={event=>startAdd(key,timeFromPosition(event.nativeEvent.offsetY))} onKeyDown={event=>{if(event.key==="Enter")startAdd(key)}}>{dayEvents.map(e=><button key={`${e.id}-${e.date}-${e.time}`} className={`week-event ${e.birthday?"birthday-event":""}`} style={{...eventStyle(e),top:timeTop(e.time),height:durationHeight(e.time,e.endTime)}} onClick={event=>{event.stopPropagation();if(!e.birthday)startEdit(events.find(item=>item.id===e.id)! )}}><b>{e.time}–{e.endTime}</b><span>{e.title}</span></button>)}</div>})}</div></div></section>}
  <footer>{members.map(m=><span key={m.email}><i className={`dot ${m.color}`}/> {m.display_name}</span>)}<span className="zone-note">{user.email} · <button className="logout" onClick={()=>supabase.auth.signOut()}>退出</button></span></footer>
  {adminOpen&&isAdmin&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setAdminOpen(false)}}><section className="admin-sheet"><div className="sheet-head"><div><p className="eyebrow">ADMIN</p><h2>日历查看权限</h2></div><button onClick={()=>setAdminOpen(false)}>×</button></div><p>每一行代表该成员可以查看谁的日历。自己的日历始终可见。</p><div className="permission-table"><table><thead><tr><th>成员</th>{members.map(owner=><th key={owner.email}>{owner.display_name}</th>)}</tr></thead><tbody>{members.map(viewer=><tr key={viewer.email}><th>{viewer.display_name}</th>{members.map(owner=>{const checked=viewer.email===owner.email||visibility.some(row=>row.viewer_email===viewer.email&&row.owner_email===owner.email);return <td key={owner.email}><input type="checkbox" checked={checked} disabled={viewer.email===owner.email} aria-label={`${viewer.display_name} 查看 ${owner.display_name}`} onChange={()=>toggleVisibility(viewer.email,owner.email)}/></td>})}</tr>)}</tbody></table></div></section></div>}
  {settingsOpen&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSettingsOpen(false)}}><section className="security-sheet"><aside className="security-profile"><span className={`security-avatar ${member.color}`}>{member.display_name.slice(0,1).toUpperCase()}</span><strong>{member.display_name}</strong><small>{user.email}</small><span>账户与安全</span></aside><div className="security-content"><div className="sheet-head"><div><p className="eyebrow">ACCOUNT &amp; SECURITY</p><h2>重设密码</h2></div><button onClick={()=>setSettingsOpen(false)}>×</button></div><p className="security-copy">修改密码前需要验证当前密码。你的成员资料、颜色和行程不会改变。</p><label>当前密码<input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="输入当前密码"/></label><hr/><label>新密码<input type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="至少 8 位"/></label><label>确认新密码<input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="再次输入新密码"/></label><p className="password-tip">建议同时包含字母和数字，不要与邮箱密码相同。</p>{passwordMessage&&<p className={`password-message ${passwordMessage==="密码已更新"?"success":""}`}>{passwordMessage}</p>}<button className="primary save" onClick={()=>updatePassword(false)} disabled={savingPassword}>{savingPassword?"正在保存…":"保存新密码"}</button></div></section></div>}
  {open&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="sheet"><div className="sheet-head"><div><p className="eyebrow">{editing?"EDIT EVENT":"NEW EVENT"}</p><h2>{editing?"编辑行程":"添加新行程"}</h2></div><button onClick={()=>setOpen(false)}>×</button></div><label>行程名称<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="例如：一起吃晚饭" autoFocus/></label><div className="two"><label>日期<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>时区<select value={draft.timezone} onChange={e=>changeDraftTimezone(e.target.value)}>{ZONES.map(timezone=><option key={timezone} value={timezone}>{ZONE_NAMES[timezone]} · {timezone}</option>)}</select></label></div><div className="two"><label>开始时间<input type="time" value={draft.time} onChange={e=>{const time=e.target.value;setDraft({...draft,time,endTime:draft.endTime===time?nextHour(time):draft.endTime})}}/></label><label>结束时间<input type="time" value={draft.endTime} onChange={e=>setDraft({...draft,endTime:e.target.value})}/></label></div><p className="timezone-help">切换时区会保持同一个真实时刻，并自动换算日期与时间；结束时间早于开始时间时表示次日结束。</p><fieldset className="participant-picker"><legend>一起的成员 <span>可选</span></legend>{members.filter(item=>item.email!==member.email).map(item=><label key={item.email} className={draft.participants.includes(item.email)?"selected":""}><input type="checkbox" checked={draft.participants.includes(item.email)} onChange={()=>toggleParticipant(item.email)}/><i className={`dot ${item.color}`}/><span>{item.display_name}</span></label>)}{members.length===1&&<p>目前还没有其他成员</p>}</fieldset><label>地点<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="输入地址"/></label><label>备注<textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})} placeholder="补充信息"/></label><p className="owner-line"><i className={`dot ${member.color}`}/> 由 {member.display_name} 添加</p>{draft.endTime===draft.time&&<p className="time-error">开始和结束时间不能相同</p>}<button className="primary save" onClick={save} disabled={!draft.title.trim()||draft.endTime===draft.time}>保存到 Shared Calendar</button>{editing&&<button className="delete" onClick={remove}>删除行程</button>}</div></div>}</main>
}
