"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { createClient, type User } from "@supabase/supabase-js";

const supabase=createClient("https://yytyntrgqkddfsliooke.supabase.co","sb_publishable_r82IW91PSRwRa_dye0g1Cw_qU0zLeDW");
type Member={email:string;display_name:string;color:string};
type CalendarEvent={id:number;title:string;date:string;time:string;endTime:string;owner:string;participants:string[];location:string;note:string;timezone:string};
const COLORS=["sage","clay","gold","rose","stone"] as const;
const COLOR_NAMES:{[key:string]:string}={sage:"鼠尾草绿",clay:"陶土橘",gold:"麦穗黄",rose:"干燥玫瑰",stone:"岩石灰"};
const ZONES=["Asia/Shanghai","Asia/Tokyo","Asia/Dubai","Europe/Berlin","Europe/London","America/Los_Angeles","America/New_York"];
const ZONE_NAMES:{[key:string]:string}={"Asia/Shanghai":"上海","Asia/Tokyo":"东京","Asia/Dubai":"迪拜","Europe/Berlin":"德国","Europe/London":"伦敦","America/Los_Angeles":"加州","America/New_York":"纽约"};
const EVENT_COLORS:{[key:string]:string}={sage:"#dce0cc",clay:"#ecd7c8",gold:"#eee2bd",rose:"#ead5d2",stone:"#dedbd1"};
const EVENT_LINES:{[key:string]:string}={sage:"#7d835f",clay:"#b87959",gold:"#b2944e",rose:"#b37b78",stone:"#817c6c"};
const HOURS=Array.from({length:25},(_,hour)=>hour);
const HOUR_HEIGHT=56;
function dateKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function nextDateKey(date:string){const [year,month,day]=date.split("-").map(Number);const value=new Date(Date.UTC(year,month-1,day+1));return `${value.getUTCFullYear()}-${String(value.getUTCMonth()+1).padStart(2,"0")}-${String(value.getUTCDate()).padStart(2,"0")}`}
function monday(d:Date){const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function timeTop(time:string){const [hour,minute]=time.split(":").map(Number);return (hour+minute/60)*HOUR_HEIGHT}
function timeFromPosition(position:number){const halfHours=Math.max(0,Math.min(47,Math.floor(position/HOUR_HEIGHT*2)));return `${String(Math.floor(halfHours/2)).padStart(2,"0")}:${halfHours%2?"30":"00"}`}
function nextHour(time:string){const [hour,minute]=time.split(":").map(Number);const total=Math.min(hour*60+minute+60,1439);return `${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`}
function minutes(time:string){const [hour,minute]=time.split(":").map(Number);return hour*60+minute}
function durationMinutes(start:string,end:string){const value=minutes(end)-minutes(start);return value>0?value:value+1440}
function durationHeight(start:string,end:string){return Math.max(40,durationMinutes(start,end)/60*HOUR_HEIGHT-4)}
function zonedParts(value:Date,timezone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(value);return Object.fromEntries(parts.map(part=>[part.type,part.value]))}
function zonedDate(date:string,time:string,timezone:string){const [year,month,day]=date.split("-").map(Number);const [hour,minute]=time.split(":").map(Number);const target=Date.UTC(year,month-1,day,hour,minute);let value=new Date(target);for(let attempt=0;attempt<3;attempt++){const shown=zonedParts(value,timezone);const represented=Date.UTC(Number(shown.year),Number(shown.month)-1,Number(shown.day),Number(shown.hour),Number(shown.minute));value=new Date(value.getTime()+target-represented)}return value}
function localInZone(value:Date,timezone:string){const parts=zonedParts(value,timezone);return {date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`}}
function convertLocal(date:string,time:string,fromZone:string,toZone:string){return localInZone(zonedDate(date,time,fromZone),toZone)}
function eventInZone(event:CalendarEvent,timezone:string){const startInstant=zonedDate(event.date,event.time,event.timezone||"Asia/Shanghai");const endInstant=new Date(startInstant.getTime()+durationMinutes(event.time,event.endTime)*60_000);const start=localInZone(startInstant,timezone);const end=localInZone(endInstant,timezone);return {...event,date:start.date,time:start.time,endTime:end.time,endDate:end.date}}

export default function Home(){
  const [user,setUser]=useState<User|null>(null);const [member,setMember]=useState<Member|null>(null);const [members,setMembers]=useState<Member[]>([]);const [authReady,setAuthReady]=useState(false);
  const [loginEmail,setLoginEmail]=useState("");const [password,setPassword]=useState("");const [signingIn,setSigningIn]=useState(false);const [authMessage,setAuthMessage]=useState("");
  const [view,setView]=useState<"month"|"week">("month");const [cursor,setCursor]=useState(new Date());const [filter,setFilter]=useState("all");const [zone,setZone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone||"Asia/Shanghai");
  const [events,setEvents]=useState<CalendarEvent[]>([]);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<CalendarEvent|null>(null);const [draft,setDraft]=useState({title:"",date:dateKey(new Date()),time:"12:00",endTime:"13:00",timezone:"Asia/Shanghai",participants:[] as string[],location:"",note:""});
  async function load(current?:User|null){const active=current??(await supabase.auth.getUser()).data.user;if(!active){setMember(null);setEvents([]);return}const email=(active.email||"").toLowerCase();const {data:memberRows}=await supabase.from("shared_calendar_members").select("email,display_name,color").order("created_at");const list=(memberRows||[]) as Member[];setMembers(list);const mine=list.find(m=>m.email.toLowerCase()===email)||null;setMember(mine);if(!mine){setEvents([]);return}const {data}=await supabase.from("shared_calendar_events").select("id,title,event_date,event_time,end_time,owner_email,participant_emails,location,note,timezone").order("event_date").order("event_time");setEvents((data||[]).map((e:any)=>({id:e.id,title:e.title,date:e.event_date,time:String(e.event_time).slice(0,5),endTime:String(e.end_time).slice(0,5),owner:e.owner_email,participants:e.participant_emails||[],location:e.location,note:e.note,timezone:e.timezone})));}
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{const u=data.session?.user||null;setUser(u);setAuthReady(true);load(u)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user||null);load(s?.user||null)});return()=>data.subscription.unsubscribe()},[]);
  const dates=useMemo(()=>{const start=view==="month"?monday(new Date(cursor.getFullYear(),cursor.getMonth(),1)):monday(cursor);return Array.from({length:view==="month"?42:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})},[cursor,view]);
  const label=view==="month"?`${cursor.getFullYear()} 年 ${cursor.getMonth()+1} 月`:`${dates[0].getMonth()+1} 月 ${dates[0].getDate()} 日 — ${dates[6].getMonth()+1} 月 ${dates[6].getDate()} 日`;
  async function signIn(event:FormEvent){event.preventDefault();if(!loginEmail.trim()||!password)return;setSigningIn(true);setAuthMessage("");const {error}=await supabase.auth.signInWithPassword({email:loginEmail.trim(),password});if(error)setAuthMessage("邮箱或密码不正确");setSigningIn(false)}
  function startAdd(date?:string,time="12:00"){setEditing(null);setDraft({title:"",date:date||dateKey(new Date()),time,endTime:nextHour(time),timezone:"Asia/Shanghai",participants:[],location:"",note:""});setOpen(true)}
  function startEdit(e:CalendarEvent){if(e.owner.toLowerCase()!==user?.email?.toLowerCase())return;setEditing(e);setDraft({title:e.title,date:e.date,time:e.time,endTime:e.endTime,timezone:e.timezone||"Asia/Shanghai",participants:e.participants||[],location:e.location||"",note:e.note||""});setOpen(true)}
  async function save(){if(!user||!member||!draft.title.trim()||draft.endTime===draft.time)return;const values={title:draft.title.trim(),event_date:draft.date,event_time:draft.time,end_time:draft.endTime,participant_emails:draft.participants,location:draft.location,note:draft.note,timezone:draft.timezone,updated_at:new Date().toISOString()};if(editing)await supabase.from("shared_calendar_events").update(values).eq("id",editing.id);else await supabase.from("shared_calendar_events").insert({...values,owner_user_id:user.id,owner_email:member.email});setOpen(false);await load(user)}
  async function remove(){if(!editing||!user)return;await supabase.from("shared_calendar_events").delete().eq("id",editing.id);setOpen(false);await load(user)}
  async function changeColor(color:string){if(!member||members.some(m=>m.email!==member.email&&m.color===color))return;const {error}=await supabase.from("shared_calendar_members").update({color}).eq("email",member.email);if(!error)await load(user)}
  if(!authReady)return <main className="login-shell"><div className="login-card"><p className="eyebrow">SHARED CALENDAR</p><h1>正在检查登录状态…</h1></div></main>;
  if(!user)return <main className="login-shell"><section className="login-card"><div className="login-mark">S</div><p className="eyebrow">PRIVATE</p><h1>Shared Calendar</h1><p className="login-copy">仅限获邀成员使用邮箱和密码登录。</p><form onSubmit={signIn}><label>邮箱地址<input type="email" autoComplete="email" value={loginEmail} onChange={e=>setLoginEmail(e.target.value)} placeholder="name@example.com"/></label><label>密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="输入密码"/></label><button className="primary login-action" type="submit" disabled={signingIn}>{signingIn?"正在登录…":"登录"}</button></form>{authMessage&&<p className="auth-message">{authMessage}</p>}</section></main>;
  if(!member)return <main className="login-shell"><section className="login-card"><div className="login-mark">!</div><p className="eyebrow">ACCESS PENDING</p><h1>邮箱尚未获邀</h1><p className="login-copy">{user.email} 已通过邮箱验证，但不在 Shared Calendar 的 5 人名单中。</p><button className="primary login-action" onClick={()=>supabase.auth.signOut()}>退出并更换邮箱</button></section></main>;
  const colors=Object.fromEntries(members.map(m=>[m.email,m.color]));
  function eventStyle(event:CalendarEvent){const participantColors=[event.owner,...event.participants].map(email=>EVENT_COLORS[colors[email]||"stone"]);const size=100/participantColors.length;const stops=participantColors.flatMap((color,index)=>[`${color} ${index*size}%`,`${color} ${(index+1)*size}%`]).join(",");return {background:`linear-gradient(to bottom, ${stops})`,borderLeftColor:EVENT_LINES[colors[event.owner]||"stone"]}}
  function matchesFilter(event:CalendarEvent){return filter==="all"||event.owner===filter||event.participants.includes(filter)}
  function toggleParticipant(email:string){setDraft({...draft,participants:draft.participants.includes(email)?draft.participants.filter(item=>item!==email):[...draft.participants,email]})}
  function changeDraftTimezone(timezone:string){const start=convertLocal(draft.date,draft.time,draft.timezone,timezone);const sourceEndDate=draft.endTime>draft.time?draft.date:nextDateKey(draft.date);const end=convertLocal(sourceEndDate,draft.endTime,draft.timezone,timezone);setDraft({...draft,date:start.date,time:start.time,endTime:end.time,timezone})}
  const shownEvents=events.map(event=>eventInZone(event,zone));
  return <main className="app-shell"><header className="topbar"><div><p className="eyebrow">PRIVATE</p><h1>Shared Calendar</h1></div><div className="top-actions"><label className="identity"><span className={`dot ${member.color}`}/><span>{member.display_name}</span></label><label className="color-choice"><span className={`dot ${member.color}`}/><select value={member.color} onChange={e=>changeColor(e.target.value)}>{COLORS.map(c=><option key={c} value={c} disabled={members.some(m=>m.email!==member.email&&m.color===c)}>{COLOR_NAMES[c]}</option>)}</select></label><button className="primary" onClick={()=>startAdd()}>＋ 新行程</button></div></header>
  <section className="toolbar"><div className="move"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+(view==="month"?-1:0),cursor.getDate()+(view==="week"?-7:0)))}>‹</button><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+(view==="month"?1:0),cursor.getDate()+(view==="week"?7:0)))}>›</button></div><strong>{label}</strong><div className="toolbar-right"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">所有成员</option>{members.map(m=><option key={m.email} value={m.email}>{m.display_name}</option>)}</select><select value={zone} onChange={e=>setZone(e.target.value)}>{ZONES.map(z=><option key={z}>{z}</option>)}</select><div className="segment"><button className={view==="week"?"active":""} onClick={()=>setView("week")}>周</button><button className={view==="month"?"active":""} onClick={()=>setView("month")}>月</button></div></div></section>
  {view==="month"?<section className="calendar month"><div className="weekdays">{["一","二","三","四","五","六","日"].map(x=><span key={x}>周{x}</span>)}</div><div className="grid">{dates.map(d=>{const key=dateKey(d);const dayEvents=shownEvents.filter(e=>e.date===key&&matchesFilter(e));return <button className={`day ${key===dateKey(new Date())?"today":""} ${d.getMonth()!==cursor.getMonth()?"muted":""}`} key={key} onClick={()=>startAdd(key)}><span className="day-number">{d.getDate()}</span><span className="event-list">{dayEvents.map(e=><span key={e.id} className="event" style={eventStyle(e)} onClick={x=>{x.stopPropagation();startEdit(events.find(item=>item.id===e.id)! )}}><b>{e.time}–{e.endTime}</b>{e.title}</span>)}</span></button>})}</div></section>:<section className="calendar week"><div className="week-scroll"><div className="week-head"><span className="time-corner">时间</span>{dates.map((d,index)=><span className={dateKey(d)===dateKey(new Date())?"current-day":""} key={dateKey(d)}>周{["一","二","三","四","五","六","日"][index]}<b>{d.getMonth()+1}/{d.getDate()}</b></span>)}</div><div className="week-body"><div className="time-axis">{HOURS.map(hour=><span key={hour} style={{top:hour*HOUR_HEIGHT}}>{String(hour).padStart(2,"0")}:00</span>)}</div>{dates.map(d=>{const key=dateKey(d);const dayEvents=shownEvents.filter(e=>e.date===key&&matchesFilter(e));return <div className={`week-column ${key===dateKey(new Date())?"today-column":""}`} key={key} role="button" tabIndex={0} aria-label={`${key} 添加行程`} onClick={event=>startAdd(key,timeFromPosition(event.nativeEvent.offsetY))} onKeyDown={event=>{if(event.key==="Enter")startAdd(key)}}>{dayEvents.map(e=><button key={e.id} className="week-event" style={{...eventStyle(e),top:timeTop(e.time),height:durationHeight(e.time,e.endTime)}} onClick={event=>{event.stopPropagation();startEdit(events.find(item=>item.id===e.id)! )}}><b>{e.time}–{e.endTime}</b><span>{e.title}</span></button>)}</div>})}</div></div></section>}
  <footer>{members.map(m=><span key={m.email}><i className={`dot ${m.color}`}/> {m.display_name}</span>)}<span className="zone-note">{user.email} · <button className="logout" onClick={()=>supabase.auth.signOut()}>退出</button></span></footer>
  {open&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="sheet"><div className="sheet-head"><div><p className="eyebrow">{editing?"EDIT EVENT":"NEW EVENT"}</p><h2>{editing?"编辑行程":"添加新行程"}</h2></div><button onClick={()=>setOpen(false)}>×</button></div><label>行程名称<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="例如：一起吃晚饭" autoFocus/></label><div className="two"><label>日期<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>时区<select value={draft.timezone} onChange={e=>changeDraftTimezone(e.target.value)}>{ZONES.map(timezone=><option key={timezone} value={timezone}>{ZONE_NAMES[timezone]} · {timezone}</option>)}</select></label></div><div className="two"><label>开始时间<input type="time" value={draft.time} onChange={e=>{const time=e.target.value;setDraft({...draft,time,endTime:draft.endTime===time?nextHour(time):draft.endTime})}}/></label><label>结束时间<input type="time" value={draft.endTime} onChange={e=>setDraft({...draft,endTime:e.target.value})}/></label></div><p className="timezone-help">切换时区会保持同一个真实时刻，并自动换算日期与时间；结束时间早于开始时间时表示次日结束。</p><fieldset className="participant-picker"><legend>一起的成员 <span>可选</span></legend>{members.filter(item=>item.email!==member.email).map(item=><label key={item.email} className={draft.participants.includes(item.email)?"selected":""}><input type="checkbox" checked={draft.participants.includes(item.email)} onChange={()=>toggleParticipant(item.email)}/><i className={`dot ${item.color}`}/><span>{item.display_name}</span></label>)}{members.length===1&&<p>目前还没有其他成员</p>}</fieldset><label>地点<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="输入地址"/></label><label>备注<textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})} placeholder="补充信息"/></label><p className="owner-line"><i className={`dot ${member.color}`}/> 由 {member.display_name} 添加</p>{draft.endTime===draft.time&&<p className="time-error">开始和结束时间不能相同</p>}<button className="primary save" onClick={save} disabled={!draft.title.trim()||draft.endTime===draft.time}>保存到 Shared Calendar</button>{editing&&<button className="delete" onClick={remove}>删除行程</button>}</div></div>}</main>
}
