create table if not exists public.shared_calendar_event_moods (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.shared_calendar_events(id) on delete cascade,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  author_email text not null,
  body text not null check (char_length(btrim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists shared_calendar_event_moods_event_created_idx
  on public.shared_calendar_event_moods(event_id, created_at);
create index if not exists shared_calendar_event_moods_author_idx
  on public.shared_calendar_event_moods(author_user_id);
create unique index if not exists shared_calendar_one_moment_per_event_idx
  on public.shared_calendar_moments(event_id) where event_id is not null;

alter table public.shared_calendar_event_moods enable row level security;
grant select, insert, delete on public.shared_calendar_event_moods to authenticated;
grant usage, select on sequence public.shared_calendar_event_moods_id_seq to authenticated;

create policy "event participants view moods"
on public.shared_calendar_event_moods for select to authenticated
using (
  exists (
    select 1 from public.shared_calendar_events e
    where e.id = event_id
      and (
        lower(e.owner_email) = lower(coalesce((select auth.jwt()) ->> 'email', ''))
        or lower(coalesce((select auth.jwt()) ->> 'email', '')) = any (
          select lower(value) from unnest(e.participant_emails) as value
        )
      )
  )
);

create policy "event participants add own moods"
on public.shared_calendar_event_moods for insert to authenticated
with check (
  author_user_id = (select auth.uid())
  and lower(author_email) = lower(coalesce((select auth.jwt()) ->> 'email', ''))
  and exists (
    select 1 from public.shared_calendar_events e
    where e.id = event_id
      and (
        lower(e.owner_email) = lower(coalesce((select auth.jwt()) ->> 'email', ''))
        or lower(coalesce((select auth.jwt()) ->> 'email', '')) = any (
          select lower(value) from unnest(e.participant_emails) as value
        )
      )
  )
);

create policy "authors delete own event moods"
on public.shared_calendar_event_moods for delete to authenticated
using (author_user_id = (select auth.uid()));
